---
# Source: metagpu-device-plugin/templates/rbac.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metagpu-device-plugin
  namespace: cnvrg
---
# Source: metagpu-device-plugin/templates/cm.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metagpu-device-plugin-config
  namespace: cnvrg
data:
  config.yaml: |
    accelerator: nvidia
    processesDiscoveryPeriod: 5
    deviceCacheTTL: 3600
    jwtSecret: topSecret
    mgctlTar: /tmp/mgctl
    mgctlAutoInject: true
    serverAddr: 0.0.0.0:50052
    memoryEnforcer: true
    deviceToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ldGFncHVAaW5zdGFuY2UiLCJ2aXNpYmlsaXR5TGV2ZWwiOiJsMCJ9.2rHykHFcHoIr-OCoPA5Am4ubf31-RJcayZnOTK6db94
    containerToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ldGFncHVAaW5zdGFuY2UiLCJ2aXNpYmlsaXR5TGV2ZWwiOiJsMSJ9.o5v6Zdi1FKXQevRjuSbABBX1vIRYgN3Daz9iXabuFFA
    deviceSharing:
      - resourceName: cnvrg.io/metagpu
        autoReshare: true
        metaGpus: 2
        uuid: [ "*" ]
---
# Source: metagpu-device-plugin/templates/rbac.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metagpu-device-plugin
  namespace: cnvrg
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - metagpu-device-plugin-config
    verbs:
      - get
      - update
---
# Source: metagpu-device-plugin/templates/rbac.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metagpu-device-plugin
  namespace: cnvrg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metagpu-device-plugin
subjects:
  - kind: ServiceAccount
    name: metagpu-device-plugin
    namespace: cnvrg
---
# Source: metagpu-device-plugin/templates/svc.yml
kind: Service
apiVersion: v1
metadata:
  name: metagpu-device-plugin
  namespace: cnvrg
  labels:
    app: "metagpu-exporter"
spec:
  selector:
    name: metagpu-device-plugin
  ports:
    - protocol: TCP
      port: 50052
      name: grcp
    - protocol: TCP
      port: 2112
      name: metrics
---
# Source: metagpu-device-plugin/templates/ds.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metagpu-device-plugin
  namespace: cnvrg
spec:
  selector:
    matchLabels:
      name: metagpu-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: metagpu-device-plugin
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      imagePullSecrets:
        - name: regcred
      hostPID: true
      hostNetwork: true
      serviceAccountName: metagpu-device-plugin
      nodeSelector:
        accelerator: nvidia
      containers:
        - name: metagpu-device-plugin
          image: "docker.io/cnvrg/metagpu-device-plugin:main"
          imagePullPolicy: Always
          command:
            - /usr/bin/mgdp
            - start
            - -c
            - /etc/metagpu-device-plugin
          ports:
            - containerPort: 50052
          securityContext:
            privileged: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MG_CTL_TOKEN
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ldGFncHVAaW5zdGFuY2UiLCJ2aXNpYmlsaXR5TGV2ZWwiOiJsMCJ9.2rHykHFcHoIr-OCoPA5Am4ubf31-RJcayZnOTK6db94
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /etc/metagpu-device-plugin
            - mountPath: /host/proc
              mountPropagation: HostToContainer
              name: proc
              readOnly: true
        - name: metagpu-exporter
          image: "docker.io/cnvrg/metagpu-device-plugin:main"
          imagePullPolicy: Always
          command:
            - /usr/bin/mgex
            - start
            - -t
            - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1ldGFncHVAaW5zdGFuY2UiLCJ2aXNpYmlsaXR5TGV2ZWwiOiJsMCJ9.2rHykHFcHoIr-OCoPA5Am4ubf31-RJcayZnOTK6db94
          ports:
            - containerPort: 2112
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: metagpu-device-plugin-config
        - hostPath:
            path: /proc
          name: proc
---
# Source: metagpu-device-plugin/templates/svcmon.yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metagpu-exporter
  namespace: cnvrg
  labels:
    app: "metagpu-exporter"
    cnvrg-infra-prometheus: cnvrg-infra-cnvrg
spec:
  selector:
    matchLabels:
      app: "metagpu-exporter"
  namespaceSelector:
    matchNames:
      - cnvrg
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: "15s"
